import type { NormalizedScorecardAnalysis } from "./scorecardAnalysis";
export type ScorecardPhotoStatus = "saved_on_device"|"waiting_for_connection"|"analyzing"|"ready_for_review"|"analysis_failed"|"applying";
export type PendingScorecardPhoto = { schemaVersion:2; queueId:string; clientImportId:string; sessionId:string; image:Blob; mimeType:string; imageFingerprint:string; createdAt:string; updatedAt:string; status:ScorecardPhotoStatus; analysis?:NormalizedScorecardAnalysis; selectedShooterCandidateId?:string|null; lastError?:string|null };
const DB="scorecard-photo-imports-v1", STORE="pending_scorecards", VERSION=2;
function openDb():Promise<IDBDatabase>{ return new Promise((resolve,reject)=>{ const req=indexedDB.open(DB,VERSION); req.onupgradeneeded=()=>{ const db=req.result; if(!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE,{keyPath:"sessionId"}); }; req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error); }); }
export async function savePendingScorecardPhoto(record: PendingScorecardPhoto){ const db=await openDb(); await new Promise<void>((res,rej)=>{ const tx=db.transaction(STORE,"readwrite"); tx.objectStore(STORE).put({...record,schemaVersion:2,updatedAt:new Date().toISOString()}); tx.oncomplete=()=>res(); tx.onerror=()=>rej(tx.error); }); db.close(); }
export async function getPendingScorecardPhoto(sessionId:string){ const db=await openDb(); const out=await new Promise<PendingScorecardPhoto|null>((res,rej)=>{ const r=db.transaction(STORE).objectStore(STORE).get(sessionId); r.onsuccess=()=>res(r.result||null); r.onerror=()=>rej(r.error); }); db.close(); return out; }
export async function deletePendingScorecardPhoto(sessionId:string){ const db=await openDb(); await new Promise<void>((res,rej)=>{ const tx=db.transaction(STORE,"readwrite"); tx.objectStore(STORE).delete(sessionId); tx.oncomplete=()=>res(); tx.onerror=()=>rej(tx.error); }); db.close(); }
export function shouldIgnoreStale(active:{sessionId:string;clientImportId:string;imageFingerprint:string}, next:{sessionId:string;clientImportId:string;imageFingerprint:string}){ return active.sessionId!==next.sessionId || active.clientImportId!==next.clientImportId || active.imageFingerprint!==next.imageFingerprint; }
export function validateReplacement(confirmed:boolean, hasPending:boolean){ return !hasPending || confirmed; }
