import type { AnalysisMiss, PrivateSessionAnalysisNote, ScorecardImportSummary } from "./deterministicSessionAnalysis";
import { buildCoachReportEvidence, sessionDate, type CoachReportDataQuality, type CoachReportEvidenceSession, type LeirdueResultRow } from "./coachReportEvidence";

export type CoachReportPeriodSession = CoachReportEvidenceSession;
export type CoachReportPeriodInput = { fromDate: string; toDate: string; sessions: CoachReportPeriodSession[]; missesBySession?: Record<string, AnalysisMiss[]>; scorecardImportsBySession?: Record<string, ScorecardImportSummary | null | undefined>; privateNotesBySession?: Record<string, PrivateSessionAnalysisNote[]>; includeNotesContext?: boolean; leirdueRows?: LeirdueResultRow[] };

function clean(value: unknown) { return String(value ?? "").trim(); }
function sessionName(session: CoachReportPeriodSession) { return clean(session.name) || "Untitled session"; }
function venueFor(session: CoachReportPeriodSession) { return clean(session.shooting_ground) || "venue not recorded"; }
function fmtPct(value: number | null) { return typeof value === "number" ? `${value.toFixed(1).replace(/\.0$/, "")}%` : "not available"; }
function periodDays(fromDate: string, toDate: string) { const from = Date.parse(`${fromDate}T00:00:00`); const to = Date.parse(`${toDate}T00:00:00`); return Number.isFinite(from) && Number.isFinite(to) ? Math.max(1, Math.round((to - from) / 86400000) + 1) : 0; }
function compactSessionList(sessions: CoachReportPeriodSession[]) { return sessions.slice(0, 4).map((session) => `${sessionDate(session)} ${sessionName(session)} (${venueFor(session)})`).join("; ") + (sessions.length > 4 ? `; plus ${sessions.length - 4} more` : ""); }
function scoreLine(item: { session: CoachReportPeriodSession; score: number | null; total: number | null; hitRate: number | null }) { return `${sessionName(item.session)} ${item.score ?? "?"}/${item.total ?? "?"} (${fmtPct(item.hitRate)})`; }
function numbered(items: string[]) { return items.map((item, index) => `${index + 1}. ${item}`); }
function aiEvidencePacket(input: CoachReportPeriodInput, evidence: ReturnType<typeof buildCoachReportEvidence>) { return { dateRange: { fromDate: input.fromDate, toDate: input.toDate }, selectedSessions: evidence.selectedSessions.map((item) => ({ id: item.session.id, date: item.date, name: sessionName(item.session), discipline: item.disciplineGroup, type: item.type, score: item.score, total: item.total, hitRate: item.hitRate, competitionLevel: item.competitionLevel, competitionLevelReason: item.competitionLevelReason, missPhase: item.phaseMisses, hasScorecardImport: item.hasScorecardImport, hasOnlyFinalScore: item.hasOnlyFinalScore })), disciplineGroups: evidence.disciplineGroups.map((group) => ({ discipline: group.discipline, selectedCount: group.sessions.length, trainingCount: group.training.length, competitionCount: group.competitions.length, averageHitRate: group.sessions.length ? group.sessions.reduce((sum, item) => sum + (item.hitRate || 0), 0) / group.sessions.filter((item) => typeof item.hitRate === "number").length || null : null, message: group.sessions.length < 2 ? "Not enough detailed data in this discipline to make a reliable recommendation." : "Discipline has enough selected data for cautious trend notes." })), trainingVsCompetition: evidence.trainingVsCompetition, startMiddleEndMissDistribution: evidence.startMiddleEndMissDistribution, preparationBeforeCompetition: { lookbackDays: evidence.preparationBeforeCompetition.lookbackDays, competitionsWithTrainingCount: evidence.preparationBeforeCompetition.competitionsWithTrainingCount, competitionCount: evidence.preparationBeforeCompetition.competitionCount, summary: evidence.preparationBeforeCompetition.summary }, repeatedMissCategories: evidence.repeatedMissCategories, notesThemes: evidence.notesThemes, leirdueFieldContexts: evidence.leirdueFieldContexts, dataQuality: evidence.dataQuality, dataQualitySummary: evidence.dataQualitySummary, privacy: { rawPrivateNotesIncluded: false, reportBodyIncludedInAnalytics: false } }; }

export function buildPeriodCoachReport(input: CoachReportPeriodInput) {
  const evidence = buildCoachReportEvidence(input);
  const repeated = evidence.repeatedMissCategories;
  const topPattern = repeated[0];
  const likelyProblem = topPattern ? `${topPattern.likelyMeaning} It appeared ${topPattern.count} times across ${topPattern.sessionNames.slice(0, 2).join("; ")}. ${topPattern.testNext}` : "No repeated miss pattern is strong enough yet. The most useful next step is to log detailed miss causes so line, lead, hold point, timing, pickup, and routine can be separated.";
  const testNext = repeated.length ? repeated.slice(0, 3).map((pattern) => `${pattern.label}: ${pattern.count} misses. ${pattern.isBroad ? `${pattern.label} is too broad to be a true diagnosis. ${pattern.testNext}` : `${pattern.likelyMeaning} ${pattern.testNext}`}`) : ["Log each miss with a precise cause: line, lead, hold point, timing, visual pickup, or routine."];
  const plan = numbered(["Recreate the top repeated miss pattern for 25–50 targets.", "Log each miss as line, lead, hold point, timing, pickup, or routine.", "Shoot one training round under competition routine.", "Add private notes after each stand about focus, fatigue, light, and decision-making."]);
  const disciplineItems = evidence.disciplineGroups.map((group) => `${group.discipline}: ${group.sessions.length} selected (${group.training.length} training, ${group.competitions.length} competition). ${group.sessions.length < 2 ? "Not enough detailed data in this discipline to make a reliable recommendation." : "Keep conclusions discipline-specific; do not merge this with other disciplines."}`);
  const fieldItems = evidence.leirdueFieldContexts.length ? evidence.leirdueFieldContexts.map((field) => `${field.eventTitle}: ${field.fieldSize} shooters, winning score ${field.winningScore ?? "?"}, placement ${field.placement ?? "?"}, median ${field.medianScore ?? "?"}, top 25% ${field.top25Score ?? "?"}. ${field.competitionLevelReason} ${field.resultStrength}`) : ["No Leirdue field-strength match was found for the selected competitions."];
  const sections = [
    { title: "Coach takeaway", items: [`Evidence-based coach report for ${evidence.selectedSessions.length} selected sessions from ${input.fromDate} to ${input.toDate}: ${evidence.trainingSessions.length} training and ${evidence.competitionSessions.length} competition.`, evidence.dataQualitySummary, topPattern ? `Top candidate: ${topPattern.label} (${topPattern.count} misses). This is a candidate to test, not a confirmed cause.` : "The selected data is not detailed enough to name a top cause confidently."] },
    { title: "Likely performance problem", items: [likelyProblem] },
    { title: "Performance context", items: fieldItems },
    { title: "Discipline-specific notes", items: disciplineItems.length ? disciplineItems : ["No selected discipline data was available."] },
    { title: "Evidence from your data", items: [`Included sessions: ${compactSessionList(input.sessions) || "none"}.`, `${evidence.scoredSessions.length} scored sessions; ${evidence.sessionsWithScorecardImportEvidence.length} with reviewed scorecard/import data; ${evidence.sessionsWithDetailedMissRows.length} with detailed miss rows; ${evidence.sessionsWithOnlyResultScore.length} with only final score; ${evidence.sessionsWithPrivateNotes.length} with private notes.`, evidence.scoreTrend.summary, evidence.bestSessions[0] ? `Best selected result: ${scoreLine(evidence.bestSessions[0])}.` : "Best result cannot be identified because score data is missing.", evidence.weakestSessions[0] ? `Weakest selected result: ${scoreLine(evidence.weakestSessions[0])}.` : "Weakest result cannot be identified because score data is missing.", `${evidence.detailedMissCount} miss rows have detailed reasons and ${evidence.broadMissCount} are broad, unknown, or missing reasons.`] },
    { title: "Training vs competition", items: [`Training average hit rate: ${fmtPct(evidence.trainingVsCompetition.trainingAverageHitRate)}. Competition average hit rate: ${fmtPct(evidence.trainingVsCompetition.competitionAverageHitRate)}. Gap: ${typeof evidence.trainingVsCompetition.gapPercentagePoints === "number" ? `${evidence.trainingVsCompetition.gapPercentagePoints.toFixed(1)} percentage points` : "not comparable"}.`, evidence.trainingVsCompetition.summary] },
    { title: "Start / finish pattern", items: [`Miss distribution from usable position data: early ${evidence.startMiddleEndMissDistribution.early}, middle ${evidence.startMiddleEndMissDistribution.middle}, late ${evidence.startMiddleEndMissDistribution.late}, unknown ${evidence.startMiddleEndMissDistribution.unknown}.`, evidence.startMiddleEndMissDistribution.interpretation] },
    { title: "Preparation before competition", items: [`${evidence.preparationBeforeCompetition.competitionsWithTrainingCount} of ${evidence.preparationBeforeCompetition.competitionCount} selected competitions had training logged in the prior ${evidence.preparationBeforeCompetition.lookbackDays} days.`, evidence.preparationBeforeCompetition.summary] },
    { title: "What to test next", items: testNext },
    { title: "Training plan for next 1–2 weeks", items: plan },
    { title: "Data quality and what to log next", items: [evidence.dataQuality === "Good" ? "Data quality is good enough for high-level priorities, but exact technique still needs field verification." : evidence.dataQuality === "Limited" ? "Data quality is limited: use this report to choose what to test next, not as proof of the root cause." : "Data quality is weak because too few selected sessions have score, miss-position, import, or detailed reason evidence.", evidence.sessionsWithScorecardImportEvidence.length ? `This report has stronger evidence from ${evidence.sessionsWithScorecardImportEvidence.length} sessions with reviewed scorecard/import data.` : "Most selected sessions only have final scores or sparse miss rows, so diagnosis confidence is limited.", input.includeNotesContext && evidence.notesThemes.length ? `Private notes suggest ${evidence.notesThemes.join(", ")}. Treat this as context, not confirmed cause.` : input.includeNotesContext ? "Private notes did not contain repeated context themes. Raw private notes are not shown." : "Notes context is available only when the toggle is on; raw private notes are not shown.", "Next logs should include score/total targets, post or target position, detailed miss reason, and short private context for wind, light, fatigue, focus, rushing, pressure, equipment, and warm-up."] },
  ];
  const plainText = sections.map((section) => `${section.title}\n${section.items.map((item) => `- ${item}`).join("\n")}`).join("\n\n");
  const dataQuality: CoachReportDataQuality = evidence.dataQuality;
  return { evidence, aiEvidencePacket: aiEvidencePacket(input, evidence), sections, plainText, hasNotesContext: input.includeNotesContext === true && evidence.sessionsWithPrivateNotes.length > 0, trainingCount: evidence.trainingSessions.length, competitionCount: evidence.competitionSessions.length, selectedSessionCount: evidence.selectedSessions.length, periodDays: periodDays(input.fromDate, input.toDate), dataQuality };
}
