"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase/client";
import { LEIRDUESTI, postTargetUnitLabel } from "@/lib/disciplines";
import { deletePendingPostSignPhoto, getPendingPostSignPhoto, listPendingPostSignPhotos, savePendingPostSignPhoto, updatePendingPostSignPhoto, type PendingPostSignPhoto } from "@/lib/targets/postSignPhotos";
import { isSimpleTargetLabel, type PostSignAnalysisResult, type PostSignPresentation } from "@/lib/targets/postSignAnalysis";
import { applyPairConventions, displayNotation, hasBlockingUnresolvedPairs, notationLabel, resolvedTypeLabel, summarizePresentations, unresolvedKinds, type PairConventionChoices } from "@/lib/targets/postSignReview";
import { detailRowsFromPosts, directions, distances, difficulties, angles, Draft, emptyPosts, ensurePostCount, isDescribed, migrateDraft, normalizePost, postHasMeaningfulData, PostTargets, PresentationType, presentationLabels, rowsFromPosts, speeds, targetTypes, template } from "@/lib/targets/postTargets";
import { configuredPostCount, normalizeDefaultPostFormat, normalizeSyncTimestamp, planSetupSave, postFormatOptions, setupTotal, shouldApplyPendingPhotoLoad, statusForPost } from "@/lib/targets/postSetupState";

const MAX_POSTS = 50;
const MAX_SOURCE_IMAGE_BYTES = 12 * 1024 * 1024;
const MAX_UPLOAD_IMAGE_BYTES = 4 * 1024 * 1024;
const draftKey = (sessionId: string) => `cpl:post-target-draft:v2:${sessionId}`;
const legacyDraftKey = (sessionId: string) => `cpl:post-target-draft:v1:${sessionId}`;
const now = () => new Date().toISOString();
type Props = { session: any; courseRows: Array<{ course_number: number }> };
type Status = "Saved on device" | "Unsynced changes" | "Syncing" | "Synced" | "Sync failed" | "Offline — saved on device" | "Waiting for connection";

export function PostTargetEditor({ session, courseRows }: Props) {
  const unit = postTargetUnitLabel(session.discipline);
  const instructionLabel = session.discipline === LEIRDUESTI ? "Post instructions" : "Stand instructions";
  const lowerUnit = unit.toLowerCase();
  const signLabel = `${lowerUnit} sign`;
  const [postCount, setPostCountState] = useState(initialPostCount(session, courseRows));
  const [posts, setPosts] = useState<PostTargets[]>(() => emptyPosts(initialPostCount(session, courseRows)));
  const [current, setCurrent] = useState(1);
  const [targetsPerPost, setTargetsPerPostState] = useState(initialTargetsPerPost(session, initialPostCount(session, courseRows)));
  const [defaultPostFormat, setDefaultPostFormat] = useState(normalizeDefaultPostFormat(session.default_post_format));
  const [manualOpen, setManualOpen] = useState(false);
  const currentPostRef = useRef(1);
  const sessionIdRef = useRef(session.id);
  const [status, setStatus] = useState<Status>(typeof navigator !== "undefined" && !navigator.onLine ? "Offline — saved on device" : "Saved on device");
  const [error, setError] = useState("");
  const [serverRows, setServerRows] = useState<any[]>([]);
  const [serverDetails, setServerDetails] = useState<any[]>([]);
  const [lastSync, setLastSync] = useState<string | undefined>();
  const [recovery, setRecovery] = useState<{ draft: Draft; serverDraft: Draft } | null>(null);
  const [pendingPhotos, setPendingPhotos] = useState<Record<number, PendingPostSignPhoto>>({});
  const [pendingPhoto, setPendingPhoto] = useState<PendingPostSignPhoto | null>(null);
  const [review, setReview] = useState<PostSignAnalysisResult | null>(null);
  const [photoUrl, setPhotoUrl] = useState("");
  const [analysisStage, setAnalysisStage] = useState("");
  const [analysisElapsed, setAnalysisElapsed] = useState(0);
  const signAbortRef = useRef<AbortController | null>(null);
  const signTimerRef = useRef<number | null>(null);
  const cameraFileRef = useRef<HTMLInputElement>(null);
  const libraryFileRef = useRef<HTMLInputElement>(null);
  const manualRef = useRef<HTMLDivElement>(null);

  useEffect(() => { currentPostRef.current = current; sessionIdRef.current = session.id; }, [current, session.id]);
  useEffect(() => { loadServerAndDraft(); const updateOnline = () => { setStatus((old) => navigator.onLine ? (old === "Offline — saved on device" || old === "Waiting for connection" ? "Unsynced changes" : old) : "Offline — saved on device"); if (navigator.onLine) void retryWaitingOnce(); }; window.addEventListener("online", updateOnline); window.addEventListener("offline", updateOnline); return () => { window.removeEventListener("online", updateOnline); window.removeEventListener("offline", updateOnline); }; }, [session.id]);
  useEffect(() => { let active = true; const capturedSessionId = session.id; void loadPendingPhotos(capturedSessionId).then((items) => { if (!shouldApplyPendingPhotoLoad(capturedSessionId, sessionIdRef.current, active)) return; setPendingPhotos(Object.fromEntries(items.map((item) => [item.postNumber, item]))); }); return () => { active = false; }; }, [session.id]);
  useEffect(() => { const item = pendingPhotos[current] || null; setPendingPhoto(item); setReview(item?.analysis || null); setError(""); }, [current, pendingPhotos]);
  useEffect(() => { if (!pendingPhoto?.image) { setPhotoUrl(""); return; } const url = URL.createObjectURL(pendingPhoto.image); setPhotoUrl(url); return () => URL.revokeObjectURL(url); }, [pendingPhoto?.queueId, pendingPhoto?.updatedAt]);
  async function loadPendingPhotos(sessionId: string) { return listPendingPostSignPhotos(sessionId); }
  function rememberPending(item: PendingPostSignPhoto | null) { setPendingPhotos((old) => { const next = { ...old }; if (item) next[item.postNumber] = item; else delete next[currentPostRef.current]; return next; }); if (item?.postNumber === currentPostRef.current && item.sessionId === sessionIdRef.current) setPendingPhoto(item); }
  function persistReview(next: PostSignAnalysisResult | null) { setReview(next); if (pendingPhoto && next) { void updatePendingPostSignPhoto(pendingPhoto.sessionId, pendingPhoto.postNumber, { analysis: next, status: "ready_for_review" }).then((updated) => { if (updated) rememberPending(updated); }); } }
  async function retryWaitingOnce() { const sessionId = sessionIdRef.current; const waiting = await listPendingPostSignPhotos(sessionId); waiting.filter((item) => item.status === "waiting_for_connection").forEach((item) => void analyze(item)); }
  function saveLocal(nextPosts: PostTargets[], nextCount = postCount, unsynced = true, syncedAt = lastSync, nextTargetsPerPost = targetsPerPost, nextDefaultPostFormat = defaultPostFormat) { const draft: Draft = { schemaVersion: 2, sessionId: session.id, postCount: nextCount, targetsPerPost: nextTargetsPerPost, defaultPostFormat: nextDefaultPostFormat, posts: nextPosts, lastLocalUpdateAt: now(), lastServerSyncAt: normalizeSyncTimestamp(syncedAt), hasUnsyncedChanges: unsynced }; localStorage.setItem(draftKey(session.id), JSON.stringify(draft)); localStorage.removeItem(legacyDraftKey(session.id)); setStatus(navigator.onLine ? (unsynced ? "Unsynced changes" : "Synced") : "Offline — saved on device"); }
  function safeDraft(raw: string) { try { return migrateDraft(JSON.parse(raw), session.id); } catch { return null; } }
  async function loadServerAndDraft() {
    const local = safeDraft(localStorage.getItem(draftKey(session.id)) || "null") || safeDraft(localStorage.getItem(legacyDraftKey(session.id)) || "null");
    if (typeof navigator !== "undefined" && !navigator.onLine) { if (local) applyDraft(local, local.hasUnsyncedChanges); setStatus("Offline — saved on device"); return; }
    const [{ data, error: loadError }, { data: details, error: detailError }] = await Promise.all([supabase.from("session_post_targets").select("*").eq("session_id", session.id).order("post_number").order("target_position"), supabase.from("session_post_details").select("*").eq("session_id", session.id).order("post_number")]);
    if (loadError || detailError) { if (local) applyDraft(local, local.hasUnsyncedChanges); setError(loadError?.message || detailError?.message || "Could not load target details."); setStatus("Sync failed"); return; }
    setServerRows(data || []); setServerDetails(details || []);
    const serverDraft = draftFromRows(data || [], details || [], session.id, initialPostCount(session, courseRows), false, initialTargetsPerPost(session, initialPostCount(session, courseRows)), normalizeDefaultPostFormat(session.default_post_format));
    if (local?.hasUnsyncedChanges) { setRecovery({ draft: local, serverDraft }); return; }
    const localSyncedAt = local?.lastServerSyncAt || local?.lastLocalUpdateAt; const serverUpdatedAt = serverDraft.lastServerSyncAt || serverDraft.lastLocalUpdateAt; const serverIsNewer = !localSyncedAt || new Date(serverUpdatedAt).getTime() > new Date(localSyncedAt).getTime(); applyDraft(serverIsNewer || !local ? serverDraft : local, false);
  }
  function applyDraft(draft: Draft, unsynced: boolean) { const syncedAt = normalizeSyncTimestamp(draft.lastServerSyncAt); setPostCountState(draft.postCount); setTargetsPerPostState(draft.targetsPerPost); setDefaultPostFormat(normalizeDefaultPostFormat(draft.defaultPostFormat)); setPosts(ensurePostCount(draft.posts, draft.postCount)); setCurrent(1); setLastSync(syncedAt); saveLocal(ensurePostCount(draft.posts, draft.postCount), draft.postCount, unsynced, syncedAt, draft.targetsPerPost, normalizeDefaultPostFormat(draft.defaultPostFormat)); }
  function mutate(nextPosts: PostTargets[], nextCount = postCount) { setPosts(nextPosts); setPostCountState(nextCount); saveLocal(nextPosts, nextCount, true); }
  function setPostCount(nextCount: number) { nextCount = Math.min(MAX_POSTS, Math.max(1, nextCount)); if (nextCount < postCount && posts.slice(nextCount).some(postHasMeaningfulData) && !window.confirm(`${unit}s above ${nextCount} contain target definitions or instructions. They will be removed only when Save setup succeeds. Continue?`)) return; mutate(ensurePostCount(posts, nextCount), nextCount); setCurrent((old) => Math.min(old, nextCount)); }
  function setTargetsPerPost(next: number) { const normalized = Math.max(1, Math.min(50, Math.round(next || 1))); setTargetsPerPostState(normalized); saveLocal(posts, postCount, true, lastSync, normalized, defaultPostFormat); }
  function replaceCurrent(nextPresentations: PostTargets["presentations"], action: string) { const post = posts[current - 1]; const sameBlank = JSON.stringify(post.presentations.map((p) => p.presentation_type)) === JSON.stringify(nextPresentations.map((p) => p.presentation_type)) && !postHasMeaningfulData(post); if (postHasMeaningfulData(post) && !sameBlank && !window.confirm(`${action} will replace the existing presentation structure, target descriptions and instructions for this ${unit.toLowerCase()}. Continue?`)) return; mutate(posts.map((p, i) => i === current - 1 ? normalizePost(current, nextPresentations, p.instructions, p.source_text) : p)); }
  function clearCurrentPost() { const post = posts[current - 1]; if (postHasMeaningfulData(post) && !window.confirm(`Clear ${unit.toLowerCase()} will remove presentations, target descriptions, instructions and extracted source text. Continue?`)) return; mutate(posts.map((p, i) => i === current - 1 ? normalizePost(current, [], "", "") : p)); }
  function addPresentation(type: PresentationType) { const post = posts[current - 1]; replacePost({ ...post, presentations: [...post.presentations, { presentation_number: post.presentations.length + 1, presentation_type: type, targets: [] }] }); }
  function removePresentation(index: number) { const p = posts[current - 1].presentations[index]; if (p.targets.some(isDescribed) && !window.confirm("This presentation contains target descriptions. Remove the full presentation and renumber later target positions?")) return; replacePost({ ...posts[current - 1], presentations: posts[current - 1].presentations.filter((_, i) => i !== index) }); }
  function changePresentation(index: number, type: PresentationType) { const p = posts[current - 1].presentations[index]; if (p.targets.some(isDescribed) && !window.confirm("Changing this structure may move descriptions to a different clay. Continue?")) return; replacePost({ ...posts[current - 1], presentations: posts[current - 1].presentations.map((x, i) => i === index ? { ...x, presentation_type: type } : x) }); }
  function replacePost(post: PostTargets) { mutate(posts.map((p, i) => i === current - 1 ? normalizePost(current, post.presentations, post.instructions, post.source_text) : p)); }
  function updateTarget(presentationIndex: number, targetIndex: number, field: string, value: string) { const post = posts[current - 1]; replacePost({ ...post, presentations: post.presentations.map((p, pi) => pi !== presentationIndex ? p : { ...p, targets: p.targets.map((t, ti) => ti === targetIndex ? { ...t, [field]: value } : t) }) }); }
  function updateInstructions(value: string) { const post = posts[current - 1]; replacePost({ ...post, instructions: value }); }

  async function sync() {
    if (!navigator.onLine) {
      setStatus("Waiting for connection");
      return;
    }

    const rows = rowsFromPosts(session.id, posts);
    const detailRows = detailRowsFromPosts(session.id, posts);
    const plan = planSetupSave({ postCount, targetsPerPost, defaultPostFormat, existingTotal: session.total_targets, confirmConflict: () => window.confirm(`This setup totals ${setupTotal(postCount, targetsPerPost)} targets, but the saved official total is ${session.total_targets}. Keep the existing official/result total and save setup only?`) });
    if (!plan.shouldContinue) { setStatus(navigator.onLine ? "Unsynced changes" : "Offline — saved on device"); return; }
    const metadata: Record<string, number | string | null> = plan.metadata;
    // Never changes result fields: own_score, winning_score, misses or imported result data.
    if ((rows.length === 0 && serverRows.length > 0) || (detailRows.length === 0 && serverDetails.length > 0)) {
      if (!window.confirm("This will delete server target definitions or post instructions for this session. Continue?")) return;
    }

    setStatus("Syncing");
    setError("");
    const syncedAt = now();

    if (rows.length) {
      const { error: upsertError } = await supabase
        .from("session_post_targets")
        .upsert(rows, { onConflict: "session_id,post_number,target_position" });
      if (upsertError) return fail(upsertError.message);
    }

    if (detailRows.length) {
      const { error: detailUpsertError } = await supabase
        .from("session_post_details")
        .upsert(detailRows, { onConflict: "session_id,post_number" });
      if (detailUpsertError) return fail(detailUpsertError.message);
    }

    const keep = new Set(rows.map((r) => `${r.post_number}:${r.target_position}`));
    const stale = serverRows.filter((r) => !keep.has(`${r.post_number}:${r.target_position}`) || r.post_number > postCount);
    for (const row of stale) {
      const { error: deleteError } = await supabase.from("session_post_targets").delete().eq("id", row.id);
      if (deleteError) return fail(deleteError.message);
    }

    const keepDetails = new Set(detailRows.map((r) => String(r.post_number)));
    const staleDetails = serverDetails.filter((r) => !keepDetails.has(String(r.post_number)) || r.post_number > postCount);
    for (const row of staleDetails) {
      const { error: deleteError } = await supabase.from("session_post_details").delete().eq("id", row.id);
      if (deleteError) return fail(deleteError.message);
    }

    const { error: metadataError } = await supabase
      .from("sessions")
      .update(metadata)
      .eq("id", session.id);
    if (metadataError) return fail(metadataError.message);

    setLastSync(syncedAt);
    saveLocal(posts, postCount, false, syncedAt);
    setStatus("Synced");
    setServerRows(rows); setServerDetails(detailRows);
  }
  function fail(message: string) { setError(message); setStatus("Sync failed"); saveLocal(posts, postCount, true); }

  async function capture(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (file) await processImage(file); }
  async function processImage(file: File) { if (pendingPhoto && !window.confirm(`Replace the existing pending sign photo or review for ${unit} ${current}?`)) return; try { const blob = await resizeImage(file); const saved = await savePendingPostSignPhoto({ sessionId: session.id, postNumber: current, image: blob, mimeType: blob.type, status: navigator.onLine ? "saved_on_device" : "waiting_for_connection" }); rememberPending(saved); setReview(null); if (navigator.onLine) void analyze(saved); } catch (e) { setError((e as Error).message); } }
  async function analyze(item = pendingPhoto) { if (!item) return; const sessionId = item.sessionId; const postNumber = item.postNumber; const isStillCurrent = () => sessionIdRef.current === sessionId && currentPostRef.current === postNumber; if (sessionIdRef.current !== sessionId) return; if (!navigator.onLine) { const updated = await updatePendingPostSignPhoto(sessionId, postNumber, { status: "waiting_for_connection", lastError: "Waiting for connection" }); if (updated) rememberPending(updated); return; } setError(""); setAnalysisStage("Preparing image"); setAnalysisElapsed(0); const analyzing = await updatePendingPostSignPhoto(sessionId, postNumber, { status: "analyzing", lastError: undefined }); if (analyzing) rememberPending(analyzing); const form = new FormData(); form.append("postNumber", String(postNumber)); form.append("image", item.image, "post-sign.jpg"); signAbortRef.current?.abort(); signAbortRef.current = new AbortController(); if (signTimerRef.current) window.clearInterval(signTimerRef.current); signTimerRef.current = window.setInterval(() => setAnalysisElapsed((v) => v + 1), 1000); try { const { data: auth } = await supabase.auth.getSession(); setAnalysisStage("Sending image"); const response = await fetch(`/api/sessions/${sessionId}/post-sign/analyze`, { method: "POST", headers: auth.session?.access_token ? { Authorization: `Bearer ${auth.session.access_token}` } : undefined, body: form, signal: signAbortRef.current.signal }); setAnalysisStage("Reading programme"); const json = await response.json().catch(() => ({})); if (signTimerRef.current) { window.clearInterval(signTimerRef.current); signTimerRef.current = null; } if (!response.ok) { const updated = await updatePendingPostSignPhoto(sessionId, postNumber, { status: "analysis_failed", lastError: json.error || "Analysis failed" }); if (updated) rememberPending(updated); if (isStillCurrent()) setError(json.error || "Analysis failed"); setAnalysisStage(""); return; } setAnalysisStage("Checking detected results"); const updated = await updatePendingPostSignPhoto(sessionId, postNumber, { status: "ready_for_review", analysis: json.result }); if (updated) rememberPending(updated); if (isStillCurrent()) { setReview(json.result); setAnalysisStage("Preparing review"); } } catch (e: any) { if (signTimerRef.current) { window.clearInterval(signTimerRef.current); signTimerRef.current = null; } if (e?.name === "AbortError") { setAnalysisStage(""); return; } const updated = await updatePendingPostSignPhoto(sessionId, postNumber, { status: "analysis_failed", lastError: "Network error. Retry analysis when connected." }); if (updated) rememberPending(updated); if (isStillCurrent()) setError("Network error. Retry analysis when connected."); setAnalysisStage(""); } }
  function cancelSignAnalysis() { signAbortRef.current?.abort(); signAbortRef.current = null; if (signTimerRef.current) { window.clearInterval(signTimerRef.current); signTimerRef.current = null; } setAnalysisStage(""); setAnalysisElapsed(0); if (pendingPhoto?.status === "analyzing") void updatePendingPostSignPhoto(pendingPhoto.sessionId, pendingPhoto.postNumber, { status: "saved_on_device" }).then((updated) => { if (updated) rememberPending(updated); }); }
  async function discardPhoto() { if (!window.confirm("Discard this pending sign photo or review?")) return; await deletePendingPostSignPhoto(session.id, current); rememberPending(null); setPendingPhoto(null); setReview(null); }
  function setReviewPresentation(index: number, patch: Partial<PostSignPresentation>) { if (!review) return; const presentations = review.presentations.map((p, i) => i === index ? normalizeReviewPresentation({ ...p, ...patch }, i) : normalizeReviewPresentation(p, i)); persistReview({ ...review, presentations }); }
  function moveReview(index: number, delta: number) { if (!review) return; const next = [...review.presentations]; const to = index + delta; if (to < 0 || to >= next.length) return; [next[index], next[to]] = [next[to], next[index]]; persistReview({ ...review, presentations: next.map(normalizeReviewPresentation) }); }
  function applyReview() { if (hasBlockingUnresolvedPairs(review)) { setError("Choose a pair notation convention or review every unresolved pair before applying."); return; } if (!review || pendingPhoto?.postNumber !== current || pendingPhoto.sessionId !== session.id) { setError("This analysis belongs to another post. Select the original post and retry."); return; } const invalid = review.presentations.flatMap((p) => p.targetLabels).find((label) => !isSimpleTargetLabel(label)); if (invalid) { setError(`Target label "${invalid}" is not a simple individual label. Use labels such as A, B or C before applying.`); return; } const post = posts[current - 1]; if (postHasMeaningfulData(post) && !window.confirm(`Apply to ${unit} ${current} will replace the current post structure, descriptions and instructions. Continue?`)) return; const presentations = review.presentations.map((p, i) => ({ presentation_number: i + 1, presentation_type: p.presentationType, targets: p.targetLabels.map((label, ti) => ({ target_position: 0, position_in_presentation: ti + 1, target_label: label.trim().toUpperCase(), target_type: "Unknown", direction: "Unknown", angle: "Unknown", speed: "Unknown", distance: "Unknown", difficulty: "Unknown", notes: "" })) })); const next = posts.map((p, i) => i === current - 1 ? normalizePost(current, presentations, review.instructions, review.rawText) : p); mutate(next); void deletePendingPostSignPhoto(session.id, current); rememberPending(null); setPendingPhoto(null); setReview(null); }

  const post = posts[current - 1] || normalizePost(current, []); const setUpCount = configuredPostCount(posts, targetsPerPost); const total = setupTotal(postCount, targetsPerPost);
  return <div className="card postTargetEditor"><h2>{unit} setup</h2><p className="small muted">{session.name}. Set the session shape, choose a {unit.toLowerCase()}, then use a sign photo or manual entry.</p>{recovery && <div className="subcard warning"><h3>Recover local draft?</h3><p className="small">A newer unsynced local draft ({new Date(recovery.draft.lastLocalUpdateAt).toLocaleString()}) exists. Server version: {new Date(recovery.serverDraft.lastLocalUpdateAt).toLocaleString()}.</p><div className="btns"><button onClick={() => { applyDraft(recovery.draft, true); setRecovery(null); }}>Restore local draft</button><button className="secondary" onClick={() => { applyDraft(recovery.serverDraft, false); setRecovery(null); }}>Use server version</button></div></div>}
    <div className="subcard setupPanel"><h3>{unit} setup</h3><div className="row"><div><label>Number of {unit.toLowerCase()}s</label><input type="number" min={1} max={MAX_POSTS} value={postCount} onChange={(e)=>setPostCount(Number(e.target.value)||1)} /></div><div><label>Expected targets per {unit.toLowerCase()}</label><input type="number" min={1} max={50} value={targetsPerPost} onChange={(e)=>setTargetsPerPost(Number(e.target.value)||1)} /></div><div><label>Default format</label><select value={defaultPostFormat} onChange={(e)=>{ setDefaultPostFormat(e.target.value); saveLocal(posts, postCount, true, lastSync, targetsPerPost, e.target.value); }}>{postFormatOptions(defaultPostFormat).map((format)=><option key={format} value={format}>{format}</option>)}</select></div></div><p className="small"><strong>{postCount} {unit.toLowerCase()}s × {targetsPerPost} targets = {total} targets</strong></p><Link href={`/sessions/${session.id}/edit`} className="small">Advanced competition settings</Link></div>
    <div className="subcard"><h3>Choose a {unit.toLowerCase()}</h3><p className="small muted">{setUpCount} of {postCount} {unit.toLowerCase()}s set up.</p><div className="postSelectorGrid">{posts.map((p, i)=>{ const n=i+1; const label=statusForPost({ post:p, expectedTargets: targetsPerPost, pendingPhoto: pendingPhotos[n] || null, syncFailed: status === "Sync failed" && n===current }); return <button type="button" key={n} className={`postSelectButton ${n===current ? "selected" : ""}`} onClick={()=>{ setCurrent(n); setManualOpen(false); }}><strong>{unit} {n}</strong><span>{label}</span></button>; })}</div><div className="btns"><button className="secondary" disabled={current<=1} onClick={()=>setCurrent(current-1)}>Previous</button><button className="secondary" disabled={current>=postCount} onClick={()=>setCurrent(current+1)}>Next</button></div></div>
    <div className="subcard currentPostCard"><h3>{unit} {current}</h3><p className="small muted">Use a clear photo of the full {signLabel}. You can take it now or choose one you photographed earlier.</p><div className="postPhotoActions"><button type="button" onClick={()=>cameraFileRef.current?.click()}>Take photo</button><button type="button" className="secondary" onClick={()=>libraryFileRef.current?.click()}>Choose from library</button><button type="button" className="secondary" onClick={()=>{ setManualOpen(true); setTimeout(()=>manualRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); }}>{post.presentations.length ? "Review and edit manually" : "Add manually"}</button></div><input ref={cameraFileRef} type="file" accept="image/*" capture="environment" onChange={capture} hidden /><input ref={libraryFileRef} type="file" accept="image/*" onChange={capture} hidden /><details><summary>Photo tips</summary><p className="small muted">Include the whole sign, keep the phone straight, avoid glare and make handwritten letters visible.</p></details>{pendingPhoto && <PhotoPanel item={pendingPhoto} photoUrl={photoUrl} unit={unit} current={current} review={review} setReview={persistReview} analyze={()=>analyze()} cancelAnalysis={cancelSignAnalysis} analysisStage={analysisStage} analysisElapsed={analysisElapsed} discard={discardPhoto} apply={applyReview} updatePresentation={setReviewPresentation} move={moveReview} add={() => review && persistReview({ ...review, presentations: [...review.presentations, normalizeReviewPresentation({ presentationNumber: 0, presentationType: "single", structuralKind: "single", targetLabels: [""], sourceText: "", sourceNotation: "", notationKind: "single", typeEvidence: "uncertain", confidence: "low", warnings: [] }, review.presentations.length)] })} remove={(i: number) => review && persistReview({ ...review, presentations: review.presentations.filter((_: PostSignPresentation, index: number) => index !== i).map(normalizeReviewPresentation) })} />}</div>
    {manualOpen && <div className="subcard" ref={manualRef}><h3>{post.presentations.length ? "Review and edit manually" : `Add manually for ${unit} ${current}`}</h3><label>{instructionLabel}</label><textarea value={post.instructions} onChange={(e)=>updateInstructions(e.target.value)} placeholder={`${unit}-wide instructions, for example LIMIT ON A!`} /><div className="btns"><button className="secondary" onClick={()=>replaceCurrent(template("report"), "5 report pairs")}>5 report pairs</button><button className="secondary" onClick={()=>replaceCurrent(template("simultaneous"), "5 simultaneous pairs")}>5 simultaneous pairs</button><button className="secondary" onClick={()=>replaceCurrent(template("singles"), "10 singles")}>10 singles</button><button className="secondary" onClick={clearCurrentPost}>Clear {unit.toLowerCase()}</button></div><div className="btns"><button onClick={()=>addPresentation("single")}>Add single</button><button onClick={()=>addPresentation("report_pair")}>Add report pair</button><button onClick={()=>addPresentation("simultaneous_pair")}>Add simultaneous pair</button><button onClick={()=>addPresentation("other_pair")}>Add other pair</button></div><div className="presentationSummary">{post.presentations.map((p)=><span key={p.presentation_number}>{p.presentation_number}. {presentationLabels[p.presentation_type]}</span>)}</div></div>}
    {manualOpen && post.presentations.map((p, pi)=><div className="subcard presentationCard" key={pi}><div className="row"><div><h3>Presentation {p.presentation_number} · {presentationLabels[p.presentation_type]}</h3></div><div><label>Structure</label><select value={p.presentation_type} onChange={(e)=>changePresentation(pi, e.target.value as PresentationType)}>{Object.entries(presentationLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div><button className="secondary" onClick={()=>removePresentation(pi)}>Remove presentation</button>{p.targets.map((t, ti)=><div className="subcard targetCard" key={t.target_position}><h4>Target position {t.target_position}{p.targets.length>1 ? ` · Pair target ${t.position_in_presentation}` : ""}</h4><div className="row"><div><label>Target label / machine</label><input value={t.target_label} onChange={(e)=>updateTarget(pi,ti,"target_label",e.target.value)} placeholder="A, B or C" /></div><div><label>Target type</label><select value={t.target_type} onChange={(e)=>updateTarget(pi,ti,"target_type",e.target.value)}>{targetTypes.map((x)=><option key={x}>{x}</option>)}</select></div><div><label>Direction</label><select value={t.direction} onChange={(e)=>updateTarget(pi,ti,"direction",e.target.value)}>{directions.map((x)=><option key={x}>{x}</option>)}</select></div></div><details><summary>More target details</summary><label>Angle</label><select value={t.angle} onChange={(e)=>updateTarget(pi,ti,"angle",e.target.value)}>{angles.map((x)=><option key={x}>{x}</option>)}</select><label>Speed</label><select value={t.speed} onChange={(e)=>updateTarget(pi,ti,"speed",e.target.value)}>{speeds.map((x)=><option key={x}>{x}</option>)}</select><label>Distance</label><select value={t.distance} onChange={(e)=>updateTarget(pi,ti,"distance",e.target.value)}>{distances.map((x)=><option key={x}>{x}</option>)}</select><label>Difficulty</label><select value={t.difficulty} onChange={(e)=>updateTarget(pi,ti,"difficulty",e.target.value)}>{difficulties.map((x)=><option key={x}>{x}</option>)}</select><label>Notes</label><textarea value={t.notes} onChange={(e)=>updateTarget(pi,ti,"notes",e.target.value)} placeholder="Optional lead, hold point or visual note" /></details></div>)}</div>)}
    <div className="stickySaveBar"><p className="small"><strong>{status === "Synced" ? "Saved and synced" : status === "Offline — saved on device" || status === "Waiting for connection" ? "Saved on this device — sync when connected" : status === "Sync failed" ? "Saved on this device — sync failed" : status === "Unsynced changes" ? "Unsaved changes" : status}</strong>{normalizeSyncTimestamp(lastSync) ? ` · Last synced ${new Date(normalizeSyncTimestamp(lastSync)!).toLocaleString()}` : ""}</p>{error && <div className="error">{error}</div>}<div className="btns"><button onClick={sync}>{status === "Sync failed" ? "Retry sync" : "Save setup"}</button><Link href={`/sessions/${session.id}`} className="button secondary">Back to competition</Link></div></div>
  </div>;
}
function PhotoPanel(props: any) {
  const { item, photoUrl, unit, current, review } = props;
  const [viewer, setViewer] = useState(false);
  const [expanded, setExpanded] = useState<number | null>(null);
  const detected = review?.detectedPostNumbers || [];
  const mismatch = review && detected.length && !detected.includes(current);
  const summary = review ? summarizePresentations(review.presentations) : null;
  const unresolved = review ? unresolvedKinds(review) : [];
  function applyConvention(choices: PairConventionChoices) {
    if (!review) return;
    const affected = review.presentations.filter((p: PostSignPresentation) => p.typeEvidence === "user_convention_required" && choices[p.notationKind as keyof PairConventionChoices] && choices[p.notationKind as keyof PairConventionChoices] !== "manual").length;
    if (affected && !confirm(`Update ${affected} unresolved pair rows with this convention?`)) return;
    props.setReview(applyPairConventions(review, choices));
  }
  return <div className="subcard postSignReviewShell">
    <p className="small"><strong>{statusText(item.status)}</strong>{item.lastError ? ` · ${item.lastError}` : ""}</p>{item.status === "analyzing" && <div className="analysisProgress"><strong>{props.analysisStage || "Analyzing"}{props.analysisElapsed > 0 ? ` · ${props.analysisElapsed} seconds` : ""}</strong><div className="indeterminateBar"/><p className="small muted">Large or detailed images can take up to about a minute.</p><button className="secondary smallButton" onClick={props.cancelAnalysis}>Cancel analysis</button></div>}
    {photoUrl && <div className="reviewReferenceBar"><button className="thumbnailButton" onClick={() => setViewer(true)}><img src={photoUrl} alt="Pending post sign thumbnail" /></button><span>{unit} {current}</span><button className="secondary smallButton" onClick={() => setViewer(true)}>View photo</button></div>}
    {viewer && photoUrl && <div className="imageLightbox" role="dialog" aria-modal="true"><button className="button" onClick={() => setViewer(false)}>Close</button><img src={photoUrl} alt="Pending post sign full size" /></div>}
    {(item.status === "saved_on_device" || item.status === "waiting_for_connection") && <button onClick={props.analyze}>Analyze now</button>}
    {item.status === "analysis_failed" && <button onClick={props.analyze}>Retry analysis</button>}
    <button className="secondary" onClick={props.discard}>Discard photo</button>
    {review && <div className="reviewWithReference">
      {photoUrl && <aside className="desktopReference"><img src={photoUrl} alt="Pending post sign" /><button className="secondary smallButton" onClick={() => setViewer(true)}>View photo</button></aside>}
      <section><h3>Review sign import</h3><p className={mismatch ? "error" : "small"}>Destination: {unit} {current}. Detected: {detected.length ? detected.join(", ") : "No readable number"}.</p>
      {summary && <div className="compactSummary"><strong>{summary.presentations} presentations · {summary.targets} target positions</strong><span>{summary.singles} singles · {summary.reportPairs} report pairs · {summary.simultaneousPairs} simultaneous pairs</span>{summary.needsReview > 0 && <span className="warning small">{summary.needsReview} items need review</span>}</div>}
      {unresolved.length > 0 && <div className="warning notationQuestion"><h4>Confirm pair notation</h4><p>This sign contains pair notation that the sign does not explain. Choose only what the sign convention means.</p>{unresolved.includes("plus") && unresolved.includes("joined") && <div className="btns"><button className="secondary smallButton" onClick={() => applyConvention({ plus: "report_pair", joined: "simultaneous_pair" })}>A+B = Report · AB = Simultaneous</button><button className="secondary smallButton" onClick={() => applyConvention({ plus: "simultaneous_pair", joined: "report_pair" })}>A+B = Simultaneous · AB = Report</button></div>}{unresolved.map((kind: any) => <label key={kind}>{notationLabel(kind)} means<select value={review.notationConventions?.[kind] || "manual"} onChange={(e) => applyConvention({ [kind]: e.target.value as any })}><option value="report_pair">Report pair</option><option value="simultaneous_pair">Simultaneous pair</option><option value="manual">Review each one manually</option></select></label>)}</div>}
      {review.warnings.map((w: string) => <div key={w} className="warning small">{w}</div>)}<label>{unit} instructions</label><textarea value={review.instructions} onChange={(e) => props.setReview({ ...review, instructions: e.target.value })} /><details><summary>Raw extracted text</summary><pre className="small">{review.rawText}</pre></details>
      <div className="compactPresentationList">{review.presentations.map((p: PostSignPresentation, i: number) => <div className="compactPresentationRow" key={i}><button className="compactPresentationMain" onClick={() => setExpanded(expanded === i ? null : i)}><strong>{i + 1}</strong><span>{displayNotation(p)}</span><span>{resolvedTypeLabel(p.presentationType)}</span>{(p.confidence !== "high" || p.warnings.length > 0) && <span aria-label="Needs attention">⚠</span>}</button><div className="compactRowActions"><button className="secondary" aria-label="Move up" onClick={() => props.move(i, -1)}>↑</button><button className="secondary" aria-label="Move down" onClick={() => props.move(i, 1)}>↓</button><button className="secondary" aria-label="Remove" onClick={() => props.remove(i)}>×</button></div>{expanded === i && <div className="expandedPresentationEditor"><label>Presentation type<select value={p.presentationType} onChange={(e) => props.updatePresentation(i, { presentationType: e.target.value as PresentationType, targetLabels: adjustLabels(p.targetLabels, e.target.value as PresentationType) })}>{Object.entries(presentationLabels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label><label>First label<input value={p.targetLabels[0] || ""} onChange={(e) => props.updatePresentation(i, { targetLabels: [e.target.value.toUpperCase(), p.targetLabels[1] || ""] })} /></label>{p.targetLabels.length > 1 && <label>Second label<input value={p.targetLabels[1] || ""} onChange={(e) => props.updatePresentation(i, { targetLabels: [p.targetLabels[0] || "", e.target.value.toUpperCase()] })} /></label>}<p className="small">Source: {p.sourceNotation || p.sourceText || "No source text"}</p>{p.warnings.map((w) => <p className="warning small" key={w}>{w}</p>)}</div>}</div>)}</div><button className="secondary" onClick={props.add}>Add presentation</button><button onClick={props.apply} disabled={hasBlockingUnresolvedPairs(review)}>Apply to {unit} {current}</button></section></div>}
  </div>;
}
function statusText(status: string) { return ({ saved_on_device: "Photo saved on device", waiting_for_connection: "Waiting for connection", analyzing: "Analyzing sign", ready_for_review: "Ready for review", analysis_failed: "Analysis failed" } as Record<string,string>)[status] || status; }
function adjustLabels(labels: string[], type: PresentationType) { const count = type === "single" ? 1 : 2; return Array.from({ length: count }, (_, i) => labels[i] || ""); }
function normalizeReviewPresentation(p: PostSignPresentation, i: number): PostSignPresentation { const structuralKind = p.structuralKind || (p.presentationType === "single" ? "single" : "pair"); return { ...p, structuralKind, sourceNotation: p.sourceNotation || p.sourceText || p.targetLabels.join(""), notationKind: p.notationKind || (structuralKind === "single" ? "single" : "other"), typeEvidence: p.typeEvidence || "uncertain", presentationNumber: i + 1, targetLabels: adjustLabels(p.targetLabels.map((x) => x.trim().toUpperCase()), p.presentationType) }; }
async function resizeImage(file: File) { if (!file.type.startsWith("image/")) throw new Error("Unsupported image type."); if (file.size > MAX_SOURCE_IMAGE_BYTES) throw new Error("Image is too large. Choose a smaller or clearer photo."); const bitmap = await createImageBitmap(file); const max = 1800; const scale = Math.min(1, max / Math.max(bitmap.width, bitmap.height)); const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(bitmap.width * scale)); canvas.height = Math.max(1, Math.round(bitmap.height * scale)); const ctx = canvas.getContext("2d"); if (!ctx) throw new Error("Could not read sign image."); ctx.drawImage(bitmap, 0, 0, canvas.width, canvas.height); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/jpeg", 0.86)); if (!blob) throw new Error("Could not prepare image for analysis."); if (blob.size > MAX_UPLOAD_IMAGE_BYTES) throw new Error("Prepared image is too large. Move closer and retake the sign photo."); return blob; }
function initialPostCount(session: any, courseRows: Array<{ course_number: number }>) { return Math.max(1, Math.min(MAX_POSTS, Number(session.post_count || session.course_count || courseRows.length || 1))); }
function initialTargetsPerPost(session: any, count: number) { return Math.max(1, Number(session.targets_per_post || (session.total_targets && count ? Math.round(session.total_targets / count) : 10))); }
function draftFromRows(rows: any[], details: any[], sessionId: string, count: number, unsynced: boolean, targetsPerPost = 10, defaultPostFormat = "5 pairs"): Draft { const posts = emptyPosts(count); for (const detail of details) { if (detail.post_number > 0) { const idx = detail.post_number - 1; posts[idx] ||= normalizePost(detail.post_number, []); posts[idx].instructions = detail.instructions || ""; posts[idx].source_text = detail.source_text || ""; } } for (const row of rows) { const p = posts[row.post_number - 1] ||= normalizePost(row.post_number, []); let pres = p.presentations.find((x) => x.presentation_number === row.presentation_number); if (!pres) { pres = { presentation_number: row.presentation_number, presentation_type: row.presentation_type, targets: [] }; p.presentations.push(pres); } pres.targets.push({ target_position: row.target_position, position_in_presentation: row.position_in_presentation, target_label: row.target_label || "", target_type: row.target_type || "Unknown", direction: row.direction || "Unknown", angle: row.angle || "Unknown", speed: row.speed || "Unknown", distance: row.distance || "Unknown", difficulty: row.difficulty || "Unknown", notes: row.notes || "" }); } const normalized = ensurePostCount(posts, Math.max(count, posts.length)); const newest = normalizeSyncTimestamp([...rows, ...details].map((r)=>r.updated_at || r.created_at).filter(Boolean).sort().at(-1)); return { schemaVersion: 2, sessionId, postCount: normalized.length, targetsPerPost, defaultPostFormat, posts: normalized, lastLocalUpdateAt: newest || now(), lastServerSyncAt: newest, hasUnsyncedChanges: unsynced }; }
