"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase/client";
import type { CourseScorecardReviewCell } from "@/lib/scorecards/courseScorecardReview";
type Proposal={evidenceId:string;courseNumber:number;sourceImageFingerprint:string;sourceEvidenceUpdatedAt:string;grid:CourseScorecardReviewCell[];reviewedScore:number|null};
export default function CourseEvidenceReviewPage(){const params=useParams<{id:string;evidenceId:string}>(),router=useRouter();const [proposal,setProposal]=useState<Proposal|null>(null),[saved,setSaved]=useState<any>(null),[score,setScore]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(true),[confirm,setConfirm]=useState(false);
 async function authHeaders(){const {data}=await supabase.auth.getSession();return {Authorization:`Bearer ${data.session?.access_token||""}`};}
 async function analyze(){setBusy(true);setMessage("");try{const response=await fetch(`/api/sessions/${params.id}/scorecard-evidence/${params.evidenceId}/analyze`,{method:"POST",headers:await authHeaders()});const json=await response.json();if(!response.ok)throw new Error(json.error?.message);setProposal(json.proposal);setScore(json.proposal.reviewedScore==null?"":String(json.proposal.reviewedScore));const {data}=await supabase.from("competition_course_scorecard_reviews").select("*").eq("session_id",params.id).eq("course_number",json.proposal.courseNumber).maybeSingle();setSaved(data);}catch(e){setMessage((e as Error).message||"Course analysis needs an internet connection. Your saved scorecard photo is still available.");}finally{setBusy(false);}}
 useEffect(()=>{void analyze();},[params.id,params.evidenceId]);
 function cycle(index:number){if(!proposal)return;const order=["unknown","hit","miss"] as const,next=order[(order.indexOf(proposal.grid[index].result)+1)%3];setProposal({...proposal,grid:proposal.grid.map((c,i)=>i===index?{...c,result:next,confidence:"high",warning:null}:c)});}
 async function save(replace=false){if(!proposal)return;setBusy(true);setMessage("");try{const response=await fetch(`/api/sessions/${params.id}/scorecard-evidence/${params.evidenceId}/apply-course`,{method:"POST",headers:{...(await authHeaders()),"Content-Type":"application/json"},body:JSON.stringify({...proposal,reviewedScore:score===""?null:Number(score),replaceExisting:replace})});const json=await response.json();if(response.status===409&&json.error?.category==="course_review_exists"){setConfirm(true);return;}if(!response.ok)throw new Error(json.error?.message);router.push(`/sessions/${params.id}`);}catch(e){setMessage((e as Error).message||"The course review could not be saved.");}finally{setBusy(false);}}
 const unknowns=proposal?.grid.filter(c=>c.result==="unknown").length||0;
 return <main className="pageShell"><section className="card"><p className="eyebrow">Saved scorecard photo</p><h1>{proposal?`Course ${proposal.courseNumber}`:"Course review"}</h1><p className="muted">25 targets</p>{busy&&!proposal&&<p>Analyzing saved photo…</p>}{message&&<p role="alert">{message}</p>}{proposal&&<><label>Confirmed course score (optional)<input inputMode="numeric" type="number" min="0" max="25" value={score} onChange={e=>setScore(e.target.value)} /></label><p className="small">{unknowns===0?"Target detail complete":score!==""?`Course score known · Target detail partial · ${unknowns} unknown`:`Course score not confirmed · Partial target detail · ${unknowns} unknown`}</p><div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(0,1fr))",gap:8,maxWidth:430}}>{proposal.grid.map((cell,index)=><button type="button" key={cell.targetNumber} onClick={()=>cycle(index)} style={{minWidth:0,minHeight:48}} aria-label={`Target ${cell.targetNumber}: ${cell.result}`}>{cell.targetNumber}<br/><small>{cell.result}</small></button>)}</div><button className="button" disabled={busy} onClick={()=>void save(false)}>Save Course {proposal.courseNumber} review</button></>}{confirm&&<div role="dialog" aria-modal="true" className="card"><p>Replace the saved Course {proposal?.courseNumber} review with this reviewed version?</p>{saved&&<p className="small">Saved review: {saved.reviewed_score==null?"score unknown":`${saved.reviewed_score}/25`} · {saved.reviewed_unknowns} unknown</p>}<button className="button" onClick={()=>{setConfirm(false);void save(true);}}>Replace saved review</button><button className="button secondary" onClick={()=>setConfirm(false)}>Keep saved review</button></div>}</section></main>}
