export type LeirdueConfidence = "high" | "medium" | "low";
export type LeirdueCategory = "recommended" | "review" | "control";

export type LeirdueCandidate = {
  date: string | null;
  name: string;
  shootingGround: string | null;
  discipline: string;
  ownScore: number | null;
  totalTargets: number | null;
  winningScore: number | null;
  leirdueUrl: string;
  listType: string | null;
  confidence: LeirdueConfidence;
  notes: string;
  category: LeirdueCategory;
  importRecommended: boolean;
  alreadyImported?: boolean;
};


export type LeirdueValidationChecklistItem = {
  label: string;
  expectedName: string;
  found: boolean;
  matchedUrl: string | null;
  parsedOwnScore: number | null;
  parsedTotalTargets: number | null;
  parsedWinningScore: number | null;
  parsedDiscipline: string | null;
  parsedShootingGround: string | null;
  status: "pass" | "partial" | "fail";
  reason: string;
};

export type LeirdueFetchDebug = {
  url: string;
  status: number | null;
  ok: boolean;
  note?: string;
};

export type LeirdueSearchDebug = {
  selectedYear: number | null;
  normalizedSearchName: string;
  eventOverviewUrls: string[];
  guessedYearOverviewUrlsTried: string[];
  discoveredYearLinks: { url: string; text: string }[];
  selectedYearLinksFound: { url: string; text: string }[];
  selectedYearOverviewUrlUsed: string | null;
  overviewYearMismatch: boolean;
  overviewDiagnostics: { url: string; containsSelectedYear: boolean; selectedYearLinkCount: number; snippet: string }[];
  noSelectedYearEventsReason: string | null;
  selectedYearEventLinks: { eventId: string; url: string; titleText: string; date: string | null; parsedYear: number | null }[];
  selectedYearEventLinksCount: number;
  selectedYearEventIdsCount: number;
  selectedDisciplineFilters: string[];
  eventsFoundBeforeFiltering: number;
  relevantEventsInspected: number;
  timedOutAtPhase: "overview" | "eventMenu" | "listeId" | "parsing" | null;
  eventLinksSkippedByReason: Record<"outsideYear" | "future" | "ranking" | "irrelevantDiscipline" | "duplicate" | "limit", number>;
  resultMenuDebug: { eventId: string; url: string; listeIdCount: number; firstListeIdUrls: string[] }[];
  prioritizedEventLinks: { eventId: string; title: string; score: number; reason: string }[];
  prioritizedListeIdLinks: { url: string; title: string; score: number; reason: string }[];
  phaseReached: "phase1" | "phase2" | "timeout" | null;
  candidatesFoundBeforeTimeout: number;
  highPriorityListeIdPagesFetched: number;
  lowPriorityListeIdPagesSkipped: number;
  timedOut: boolean;
  limitReached: boolean;
  whichLimit: string | null;
  message: string | null;
  lastFetchUrl: string | null;
  errorMessage: string | null;
  eventIdsFound: string[];
  eventIdsInspected: string[];
  eventDatesParsed: Record<string, string | null>;
  eventYearsFound: Record<string, number>;
  eventYearsInspected: Record<string, number>;
  candidatesByYear: Record<string, number>;
  skippedOutsideSelectedYear: number;
  eventIdsSkippedOutsideYear: string[];
  eventIdsSkippedFuture: string[];
  completedEventsInspected: number;
  futureEventsSkipped: number;
  listeIdLinksByEvent: Record<string, string[]>;
  shooterMatchSnippets: { url: string; snippet: string }[];
  hiddenControlCandidates: number;
  fetchedUrls: LeirdueFetchDebug[];
  eventLinksFound: number;
  resultLinksFound: number;
  eventPagesFetched: number;
  eventInfoPagesFetched: number;
  eventResultMenuPagesFetched: number;
  listeIdLinksExtracted: number;
  listeIdLinksFromResultMenus: number;
  listeIdPagesFetched: number;
  listeIdShooterPagesFound: number;
  firstListeIdUrlsInspected: string[];
  firstShooterMatchUrls: string[];
  listInspectionLimitReached: boolean;
  resultMenuDiagnostics: { eventUrl: string; contains: Record<string, boolean>; snippet: string }[];
  validationUrlsInspected: number;
  validationShooterMatches: number;
  candidateCategoryCounts: Record<LeirdueCategory, number>;
  candidateConfidenceCounts: Record<LeirdueConfidence, number>;
  duplicatesRemoved: number;
  candidatesWithOwnScore: number;
  candidatesWithWinningScore: number;
  candidatesWithTotalTargets: number;
  candidatesWithShootingGround: number;
  recommendedWithShootingGround: number;
  recommendedWithCompleteScore: number;
  candidateDebugRows: { url: string; name: string; date: string | null; discipline: string; shootingGround: string | null; shootingGroundSource: string; ownScore: number | null; totalTargets: number | null; winningScore: number | null; category: LeirdueCategory; confidence: LeirdueConfidence; importRecommended: boolean; reason: string; hiddenFromNormalUi: boolean; notes: string }[];
  validationChecklist: LeirdueValidationChecklistItem[];
  pagesInspected: number;
  shooterPagesFound: number;
  candidateRowsCreated: number;
  rejectedReasons: string[];
  candidateReasons: string[];
  firstUsefulSnippet: string | null;
};

export type LeirdueSearchResult = {
  candidates: LeirdueCandidate[];
  debug: LeirdueSearchDebug;
};
