export type LeirdueConfidence = "high" | "medium" | "low";
export type LeirdueCategory = "recommended" | "review" | "control";

export type LeirdueDuplicateStatus = "new" | "possible" | "exact";
export type LeirdueNameMatchReason = "exact normalized match" | "diacritic-insensitive match" | "partial/initial match" | "fuzzy/possible match" | "no match";
export type LeirdueCheckedListStatus = "parsed" | "no matching shooter" | "unsupported format" | "failed fetch" | "no score rows found" | "possible duplicate";

export type LeirdueDuplicateMatch = {
  id: string;
  reason: string;
  exact: boolean;
};

export type LeirdueCandidate = {
  date: string | null;
  name: string;
  shootingGround: string | null;
  discipline: string;
  ownScore: number | null;
  totalTargets: number | null;
  winningScore: number | null;
  maxScore?: number | null;
  placement?: number | null;
  seriesScores?: number[];
  shooterName?: string | null;
  shooterClass?: string | null;
  stevneId?: string | null;
  listeId?: string | null;
  warnings?: string[];
  duplicateStatus?: LeirdueDuplicateStatus;
  duplicateMatches?: LeirdueDuplicateMatch[];
  shooterMatchStatus?: "matched_to_you" | "possible_match" | "unmatched" | null;
  shooterMatchReason?: LeirdueNameMatchReason | null;
  allowDuplicateSave?: boolean;
  leirdueUrl: string;
  listType: string | null;
  confidence: LeirdueConfidence;
  notes: string;
  category: LeirdueCategory;
  importRecommended: boolean;
  alreadyImported?: boolean;
};

export type LeirdueDebugParseInput = {
  url: string;
  shooterName: string;
  year?: number | null;
  selectedDisciplines?: string[];
};

export type LeirdueDebugParseResult = {
  url: string;
  status: number | null;
  ok: boolean;
  error: string | null;
  pageTitle: string | null;
  eventTitle: string | null;
  listTitle: string | null;
  normalizedShooterName: string;
  shooterFound: boolean;
  rawSnippet: string | null;
  parsedRow: string | null;
  parsedNumbers: number[];
  parsedSeriesScores: number[];
  ownScore: number | null;
  totalTargets: number | null;
  winningScore: number | null;
  discipline: string | null;
  shootingGround: string | null;
  date: string | null;
  category: LeirdueCategory | null;
  confidence: LeirdueConfidence | null;
  importRecommended: boolean;
  parserNotes: string[];
  firstUsefulSnippet: string | null;
  candidateRows: { text: string; numbers: number[]; total: number | null; seriesScores: number[]; containsShooter: boolean }[];
  topCompetitorTotals: { row: string; total: number; numbers: number[] }[];
  candidate: LeirdueCandidate | null;
};

export type LeirdueManualLinkParseResult = {
  url: string;
  status: number | null;
  ok: boolean;
  error: string | null;
  pageTitle: string | null;
  eventTitle: string | null;
  listTitle: string | null;
  date: string | null;
  discipline: string | null;
  shootingGround: string | null;
  stevneId: string | null;
  listeId: string | null;
  parserNotes: string[];
  listChoices: { url: string; label: string; listeId: string | null }[];
  candidates: LeirdueCandidate[];
};


export type LeirdueValidationChecklistItem = {
  label: string;
  expectedName: string;
  found: boolean;
  matchedUrl: string | null;
  parsedOwnScore: number | null;
  parsedTotalTargets: number | null;
  parsedWinningScore: number | null;
  parsedDiscipline: string | null;
  parsedShootingGround: string | null;
  status: "pass" | "partial" | "fail";
  reason: string;
};

export type LeirdueCheckedListDebug = {
  eventName: string | null;
  date: string | null;
  sourceUrl: string;
  stevneId: string | null;
  listeId: string | null;
  status: LeirdueCheckedListStatus;
  rowsFound: number;
  candidateShooterRows: number;
  reason: string | null;
};

export type LeirdueCoverageDebug = {
  eventsChecked: number;
  resultListsChecked: number;
  rowsParsed: number;
  confirmedMatches: number;
  possibleMatches: number;
  alreadyImported: number;
  ignoredOrFailed: number;
  failedOrUnsupportedPages: number;
};

export type LeirdueFetchDebug = {
  url: string;
  status: number | null;
  ok: boolean;
  note?: string;
};

export type LeirdueSearchDebug = {
  selectedYear: number | null;
  normalizedSearchName: string;
  eventOverviewUrls: string[];
  guessedYearOverviewUrlsTried: string[];
  discoveredYearLinks: { url: string; text: string }[];
  selectedYearLinksFound: { url: string; text: string }[];
  selectedYearOverviewUrlUsed: string | null;
  overviewYearMismatch: boolean;
  overviewDiagnostics: { url: string; containsSelectedYear: boolean; selectedYearLinkCount: number; snippet: string }[];
  noSelectedYearEventsReason: string | null;
  selectedYearEventLinks: { eventId: string; url: string; titleText: string; eventTitle?: string; organizerText?: string | null; dateText?: string | null; rawRowSnippet?: string; titleParseSource?: "anchorText" | "rowSnippet" | "fallback"; date: string | null; parsedYear: number | null; overviewMatchedYear?: boolean; actualEventYear?: number | null; actualEventDate?: string | null; actualDateText?: string | null; inspected?: boolean; skippedReason?: string | null }[];
  eventTitleDebugRows: { eventId: string; title: string; organizer: string | null; dateText: string | null; rawRowSnippet: string; titleParseSource: "anchorText" | "rowSnippet" | "fallback"; priority: number; reason: string; selectedDisciplineMatches: string[]; overviewMatchedYear?: boolean; actualEventYear?: number | null; actualEventDate?: string | null; actualDateText?: string | null; inspected?: boolean; skippedReason?: string | null }[];
  selectedYearEventLinksCount: number;
  selectedYearEventIdsCount: number;
  actualSelectedYearEventsCount: number;
  unknownYearFallbackEventsCount: number;
  actualYearMismatchSkippedCount: number;
  knownTorbjorn2025Debug: { eventId: string; listeId: string; discovered: boolean; inspected: boolean; resultMenuFetched: boolean; listeIdsFound: string[]; listeQueued: boolean; listeScanned: boolean; reason: string | null }[];
  regressionPriorityApplied: boolean;
  regressionEventsBoosted: string[];
  eventBatchesProcessed: number;
  eventQueueRemainingWhenStopped: number;
  eventStopReason: "completeCandidatesFound" | "enough candidates" | "max scan pages" | "max shooter pages" | "timeout" | "result menu limit" | "event queue exhausted" | null;
  candidatesFoundPerBatch: number[];
  listeIdPagesScannedPerBatch: number[];
  completeCandidatesFound: number;
  completeCandidatesTotal: number;
  visibleCompleteCandidates: number;
  hiddenCompleteCandidates: number;
  importableCompleteCandidates: number;
  targetReachedBy: string | null;
  partialCandidatesFound: number;
  lowQualityCandidatesFound: number;
  searchContinuedBecauseOnlyLowQualityCandidates: boolean;
  percentageHeavyCandidates: number;
  expectedCandidateTarget: number;
  visibleCandidatesCount: number;
  hiddenLowQualityCandidatesCount: number;
  completeCandidatesFoundList: { url: string; name: string; date: string | null; ownScore: number | null; totalTargets: number | null; winningScore: number | null }[];
  nextUnscannedEventQueue: { eventId: string; title: string; actualEventYear: number | null; priority: number; reason: string }[];
  continuationAvailable: boolean;
  continuationReason: string | null;
  scannedListeIdTotal: number;
  scannedEventTotal: number;
  remainingEventQueueCount: number;
  confirmedSelectedYearEventsRemaining: number;
  likelySelectedYearEventsRemaining: number;
  unknownYearSelectedTextEventsRemaining: number;
  unknownYearEventsRemaining: number;
  outsideYearFallbackEventsRemaining: number;
  pendingListeIdQueueRemaining: number;
  oldYearEventsSkippedThisBatch: number;
  likelySelectedYearEventsProcessedThisBatch: number;
  autoStoppedBecauseOnlyOldFallbackRemains: boolean;
  continuationDisabledReason: string | null;
  batchNumber: number;
  completeCandidatesFoundTotal: number;
  visibleCandidatesCountTotal: number;
  hiddenLowQualityCandidatesCountTotal: number;
  previousVisibleCandidatesCount: number;
  returnedVisibleCandidatesCount: number;
  accumulatedCompleteCandidatesCount: number;
  queuedThisBatch: number;
  scannedThisBatch: number;
  fetchedThisBatch: number;
  eventMenusFetchedThisBatch: number;
  timeBudgetReason: string | null;
  continuationStopReason: string | null;
  pendingListeIdQueueAtStart: number;
  pendingListeIdQueueAtEnd: number;
  listeIdsQueuedThisBatch: number;
  listeIdsScannedThisBatch: number;
  scanFirstMode: boolean;
  batchStopReason: string | null;
  candidateQualityStopReason: "completeCandidatesFound" | "timeout" | "scanLimit" | "eventQueueExhausted" | "shooterPageLimit" | "resultMenuLimit" | null;
  selectedDisciplineFilters: string[];
  eventsFoundBeforeFiltering: number;
  selectedYearEventLinksBeforeFilter: number;
  hardSkippedUnselectedDiscipline: number;
  hardSkippedRankingOrControl: number;
  genericFallbackEventsAdded: number;
  selectedYearEventLinksAfterSoftFilter: number;
  relevantEventsInspected: number;
  timedOutAtPhase: "overview" | "eventMenu" | "listeId" | "parsing" | null;
  eventLinksSkippedByReason: Record<"outsideYear" | "future" | "ranking" | "irrelevantDiscipline" | "duplicate" | "limit", number>;
  resultMenuDebug: { eventId: string; url: string; listeIdCount: number; firstListeIdUrls: string[] }[];
  prioritizedEventLinks: { eventId: string; title: string; score: number; reason: string; titleParseSource?: "anchorText" | "rowSnippet" | "fallback"; selectedDisciplineMatches?: string[]; overviewMatchedYear?: boolean; actualEventYear?: number | null; actualEventDate?: string | null; inspected?: boolean; skippedReason?: string | null }[];
  prioritizedListeIdLinks: { url: string; title: string; score: number; reason: string }[];
  phaseReached: "phase1" | "phase2" | "timeout" | null;
  candidatesFoundBeforeTimeout: number;
  highPriorityListeIdPagesFetched: number;
  lowPriorityListeIdPagesSkipped: number;
  listeIdPagesQueued: number;
  listeIdPagesScannedForName: number;
  shooterPagesParsed: number;
  scanStoppedReason: "targetReached" | "timeout" | "scanLimit" | "shooterPageLimit" | "eventQueueExhausted" | null;
  candidatesFoundAfterDiscovery: number;
  candidatesFoundAfterScan: number;
  resultMenusBeforeFirstListeIdScan: number;
  timedOutBeforeFirstListeIdScan: boolean;
  timedOut: boolean;
  limitReached: boolean;
  whichLimit: string | null;
  message: string | null;
  lastFetchUrl: string | null;
  errorMessage: string | null;
  eventIdsFound: string[];
  eventIdsInspected: string[];
  eventDatesParsed: Record<string, string | null>;
  eventYearsFound: Record<string, number>;
  eventYearsInspected: Record<string, number>;
  candidatesByYear: Record<string, number>;
  skippedOutsideSelectedYear: number;
  eventIdsSkippedOutsideYear: string[];
  eventIdsSkippedFuture: string[];
  completedEventsInspected: number;
  futureEventsSkipped: number;
  listeIdLinksByEvent: Record<string, string[]>;
  shooterMatchSnippets: { url: string; snippet: string }[];
  hiddenControlCandidates: number;
  coverage: LeirdueCoverageDebug;
  checkedLists: LeirdueCheckedListDebug[];
  fetchedUrls: LeirdueFetchDebug[];
  eventLinksFound: number;
  resultLinksFound: number;
  eventPagesFetched: number;
  eventInfoPagesFetched: number;
  eventResultMenuPagesFetched: number;
  listeIdLinksExtracted: number;
  listeIdLinksFromResultMenus: number;
  listeIdPagesFetched: number;
  listeIdShooterPagesFound: number;
  firstListeIdUrlsInspected: string[];
  firstShooterMatchUrls: string[];
  listInspectionLimitReached: boolean;
  resultMenuDiagnostics: { eventUrl: string; contains: Record<string, boolean>; snippet: string }[];
  validationUrlsInspected: number;
  validationShooterMatches: number;
  candidateCategoryCounts: Record<LeirdueCategory, number>;
  candidateConfidenceCounts: Record<LeirdueConfidence, number>;
  duplicatesRemoved: number;
  candidatesWithOwnScore: number;
  candidatesWithWinningScore: number;
  candidatesWithTotalTargets: number;
  candidatesWithShootingGround: number;
  recommendedWithShootingGround: number;
  recommendedWithCompleteScore: number;
  candidateDebugRows: { url: string; name: string; date: string | null; discipline: string; shootingGround: string | null; shootingGroundSource: string; ownScore: number | null; totalTargets: number | null; winningScore: number | null; category: LeirdueCategory; confidence: LeirdueConfidence; importRecommended: boolean; reason: string; hiddenFromNormalUi: boolean; totalTargetsSource: string | null; inferredTotalTargets: number | null; inferenceConfidence: string | null; hiddenReason: string | null; notes: string }[];
  validationChecklist: LeirdueValidationChecklistItem[];
  pagesInspected: number;
  shooterPagesFound: number;
  candidateRowsCreated: number;
  rejectedReasons: string[];
  candidateReasons: string[];
  firstUsefulSnippet: string | null;
  cacheDiagnostics: {
    cacheUsed: boolean;
    cacheReadOk: boolean;
    cacheWriteOk: boolean;
    cacheNotUsedReason: string | null;
    cachedCandidatesFound: number;
    cachedImportableCandidatesFound: number;
    cachedInvalidListsFound: number;
    cachedCandidatesLoaded: number;
    cacheScopeComplete: boolean;
    cacheScopeStatus: "unknown" | "incomplete" | "complete" | "failed";
    continuationRequired: boolean;
    resumedFromSavedProgress: boolean;
    processedEventsThisBatch: number;
    processedListeIdsThisBatch: number;
    processedThisBatch: number;
    previouslyProcessed: number;
    previouslyProcessedBeforeBatch: number;
    previouslyProcessedAfterBatch: number;
    remainingWork: number | null;
    remainingWorkBeforeBatch: number | null;
    remainingWorkAfterBatch: number | null;
    skippedAlreadyProcessedEvents: number;
    skippedAlreadyProcessedListeIds: number;
    restoredEventQueueCount: number;
    restoredListeIdQueueCount: number;
    batchTimeLimitMs: number | null;
    batchStopReason: string | null;
    noProgressReason: string | null;
    frontendContinuationMode: string | null;
    liveRefreshStarted: boolean;
    liveRefreshReason: string | null;
    crawlMarkedComplete: boolean;
    crawlStopReason: string | null;
    progressWriteOk: boolean;
    progressWriteError: string | null;
    liveCandidatesFound: number;
    cacheEventHits: number;
    cacheListHits: number;
    cacheMisses: number;
    staleCacheRefreshed: number;
    staleCacheRows: number;
    liveEventFetches: number;
    liveMenuFetches: number;
    liveListFetches: number;
    liveFetchesStarted: number;
    liveFetchesSkippedBecauseCached: number;
    liveFetchesSkippedBecauseCachedInvalid: number;
    invalidCachedListsSkipped: number;
    invalidLiveListsCached: number;
    elapsedMs: number | null;
    stopReason: string | null;
    repeatedSearchShouldBeFaster: boolean;
    serviceRoleCacheWriteEnabled: boolean;
    cacheWriteErrors: string[];
    cacheWriteWarnings: string[];
    cacheReadErrors: string[];
  };
};

export type LeirdueSearchResult = {
  candidates: LeirdueCandidate[];
  debug: LeirdueSearchDebug;
  continuationToken?: string | null;
};
