alter table public.training_score_sheets add column programme_snapshot jsonb;
create or replace function public.is_valid_score_sheet_programme_snapshot(snapshot jsonb) returns boolean language plpgsql immutable set search_path=public as $$
declare area jsonb; presentation jsonb;
begin
 if jsonb_typeof(snapshot) is distinct from 'object' or jsonb_typeof(snapshot->'schemaVersion') is distinct from 'number' or snapshot->>'schemaVersion'<>'1' or jsonb_typeof(snapshot->'snapshotId') is distinct from 'string' or nullif(btrim(snapshot->>'snapshotId'),'') is null or jsonb_typeof(snapshot->'name') is distinct from 'string' or nullif(btrim(snapshot->>'name'),'') is null or jsonb_typeof(snapshot->'family') is distinct from 'string' or snapshot->>'family' not in ('compak_menu','sporttrap_menu','custom') or jsonb_typeof(snapshot->'source') is distinct from 'string' or snapshot->>'source' not in ('built_in','custom','legacy') or jsonb_typeof(snapshot->'modified') is distinct from 'boolean' or not(snapshot?'sourceOrganisation') or jsonb_typeof(snapshot->'sourceOrganisation') not in ('string','null') or not(snapshot?'sourceVersion') or jsonb_typeof(snapshot->'sourceVersion') not in ('string','null') or not(snapshot?'templateId') or jsonb_typeof(snapshot->'templateId') not in ('string','null') or jsonb_typeof(snapshot->'machineVocabulary') is distinct from 'array' or jsonb_array_length(snapshot->'machineVocabulary')=0 or exists(select 1 from jsonb_array_elements(snapshot->'machineVocabulary') v where jsonb_typeof(v)<>'string' or nullif(btrim(v#>>'{}'),'') is null) or jsonb_typeof(snapshot->'areas') is distinct from 'array' or jsonb_array_length(snapshot->'areas')=0 then return false; end if;
 for area in select value from jsonb_array_elements(snapshot->'areas') loop
  if jsonb_typeof(area) is distinct from 'object' or jsonb_typeof(area->'areaNumber') is distinct from 'number' or area->>'areaNumber' !~ '^[1-9][0-9]*$' or jsonb_typeof(area->'presentations') is distinct from 'array' or jsonb_array_length(area->'presentations')=0 then return false; end if;
  for presentation in select value from jsonb_array_elements(area->'presentations') loop
   if jsonb_typeof(presentation) is distinct from 'object' or jsonb_typeof(presentation->'id') is distinct from 'string' or nullif(btrim(presentation->>'id'),'') is null or jsonb_typeof(presentation->'type') is distinct from 'string' or presentation->>'type' not in ('single','report_pair','simultaneous_pair','unknown') or (presentation->>'type'='unknown' and snapshot->>'source'<>'legacy') or not(presentation?'firstMachine') or jsonb_typeof(presentation->'firstMachine') not in ('string','null') or not(presentation?'secondMachine') or jsonb_typeof(presentation->'secondMachine') not in ('string','null') then return false; end if;
  end loop;
 end loop;
 if snapshot->>'family'='compak_menu' and snapshot->>'source'<>'legacy' and (jsonb_array_length(snapshot->'areas')<>5 or exists(select 1 from jsonb_array_elements(snapshot->'areas') a where (select coalesce(sum(case when p->>'type' in ('report_pair','simultaneous_pair') then 2 else 1 end),0) from jsonb_array_elements(a->'presentations') p)<>5)) then return false; end if;
 return true;
exception when others then return false; end $$;
alter table public.training_score_sheets add constraint training_score_sheets_programme_snapshot_shape check(programme_snapshot is null or public.is_valid_score_sheet_programme_snapshot(programme_snapshot));
comment on column public.training_score_sheets.programme_snapshot is 'Independent event programme snapshot with template provenance and ordered presentations; never resolved dynamically from current built-ins.';
create or replace function public.is_complete_score_sheet_programme_snapshot(snapshot jsonb) returns boolean language sql immutable set search_path=public as $$ select public.is_valid_score_sheet_programme_snapshot(snapshot) and not exists(select 1 from jsonb_array_elements(snapshot->'areas') area,jsonb_array_elements(area->'presentations') presentation where presentation->>'type'<>'unknown' and (nullif(btrim(presentation->>'firstMachine'),'') is null or not(snapshot->'machineVocabulary' @> jsonb_build_array(presentation->'firstMachine')) or (presentation->>'type' in ('report_pair','simultaneous_pair') and (nullif(btrim(presentation->>'secondMachine'),'') is null or presentation->>'firstMachine'=presentation->>'secondMachine' or not(snapshot->'machineVocabulary' @> jsonb_build_array(presentation->'secondMachine')))))) $$;
create or replace function public.validate_competition_programme_on_finalize() returns trigger language plpgsql set search_path=public as $$ begin if new.session_type='competition' and new.competition_status='finalized' and old.competition_status is distinct from 'finalized' and new.programme_snapshot is not null and not public.is_complete_score_sheet_programme_snapshot(new.programme_snapshot) then raise exception using errcode='22023',message='Complete the event programme before finalizing.'; end if; return new; end $$;
create trigger competition_programme_finalize_guard before update on public.training_score_sheets for each row execute function public.validate_competition_programme_on_finalize();
revoke execute on function public.is_valid_score_sheet_programme_snapshot(jsonb) from public,anon; revoke execute on function public.is_complete_score_sheet_programme_snapshot(jsonb) from public,anon; grant execute on function public.is_valid_score_sheet_programme_snapshot(jsonb) to authenticated,service_role; grant execute on function public.is_complete_score_sheet_programme_snapshot(jsonb) to authenticated,service_role; revoke execute on function public.validate_competition_programme_on_finalize() from public,anon,authenticated;
